swagger: '2.0'
info:
  description: Swagger API for our application " Fitness Tracker".
  version: 1.0.0
  title: Fitness Track
  termsOfService: "http://swagger.io/terms/"

  contact:
    email: s542301@nwmissouri.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: "/api"
tags:
- name: Users
  description: user creates an account by logging and giving the credentials
- name: exercises
  description: exercises are displayed for week. User sets particular exercises for each day.

paths:
  /addexercises:
    post:
      tags:
      - Users
      summary: Can add exercises to their account.
      operationId: exercises are added
      description: add exercises to their account
      responses:
        201:
          description: added workouts
    
    get:
      tags:
      - Users
      summary: "Get a list nutrition,goals"
      description: ""
      operationId: "getUsers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input" 
     
  /Scheduling :
    get:
      tags:
      - exercises
      summary: time limit is set for the workouts based on their their energy levels 
      description: If user isn't in mood of doing user can schedule the time limit to zero 
      operationId: schedule
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        405:
          description: Invalid input

    post:
      tags:
      - exercises
      summary: Can remove activities from their account.
      operationId: activities are removed
      description: removed activities from their account
      responses:
        201:
          description: removed activities
definitions:
  Users:
    type: object
    required:
    - name
    - gender
    properties:
      email-id:
        type: string
  exercises:
    required:
    - name
    properties:
      name:
        type: string
      weekday:
        type: string

schemes:
 - https
host: fitness-trackk.herokuapp.com
